refresh_subscriptions_rssreader:
  cron: "*/30 * * * *"
  class: "RefreshSubscriptionsJob"
  queue: rssreader

remove_old_entries_rssreader:
  cron: "0 0 * * *"
  class: "RemoveOldEntriesJob"
  queue: rssreader